### ISSUE TITLE
接入第三方crash监控sdk 有无测试过？

### ISSUE THREAD

**Issue by colin-phang** [android-notes/Cockroach#12]
有些第三方crash监控，例如腾讯的BUGLY，如果实现原理 也是设置了Thread.setDefaultUncaughtExceptionHandler，那么Cockroach可能让这些监控完全失效了，又或者是使Cockroach无法捕获子线程异常。

**Comment by android-notes** [comment]
在bugly前初始化Cockroach就不会覆盖了，或者复制一份Cockroach代码，把Thread.setDefaultUncaughtExceptionHandler逻辑去掉
