### ISSUE TITLE
你QQ多少想请教你几个问题 

### ISSUE THREAD

**Issue by youxin11544** [android-notes/Cockroach#13]

**Comment by android-notes** [comment]
直接在这下面问就好了，记得@ 下我  @youxin11544

**Comment by youxin11544** [comment]
ActivityThread的main方法中已经执行过了Looper.loop();//开启死循环，挨个执行Message        然后我们又在install 方法中又执行了Looper.loop();       那么消息最后在那个循环执行，我有点搞不懂，Looper.loop()这个方法可以执行多次吗？ @android-notes

**Comment by android-notes** [comment]
当然是在install 方法中的Looper.loop();执行循环，Looper.loop()没必要执行多次，具体见原理分析 @youxin11544
