### ISSUE TITLE
生命周期出了Bug，捕获还是会崩溃

### ISSUE THREAD

**Issue by junwen0814** [android-notes/Cockroach#14]
非生命周期出了Bug能够捕获到，没什么问题，但是在生命周期里面捕获到了问题，虽然能捕获到，但是他几秒后还是会蹦掉，没办法让他不蹦吗？

**Comment by android-notes** [comment]
确定是崩溃吗，还是一直黑屏，有日志吗 @junwen0814

**Comment by junwen0814** [comment]
黑屏吧，就感觉直接挂了。

**Comment by android-notes** [comment]
黑屏不是挂，这个只能保证java crash不会导致崩溃，并不知道捕获到crash该如何恢复 @junwen0814

**Comment by junwen0814** [comment]
可是黑屏了，不是体验更差，用户都不知道咋回事了？只能退出清内存了。

**Comment by android-notes** [comment]
不建议一开始就装载，建议后台统计到crash时，若开启cockroach后不影响其他功能，可以通过后台控制当进入该Activity时装载，退出该Activity时卸载 @junwen0814
