### ISSUE TITLE
后端控制开启和卸载,是怎么控制?

### ISSUE THREAD

**Issue by qingguoguo** [android-notes/Cockroach#16]
当线上发现进入某个Activity有大量crash时，若装载Cockroach后不影响APP运行，不影响用户体检，就可以通过后端控制来自动开启Cockroach，当退出这个Activity后自动卸载Cockroach。这样其他用户再次进入该Activity就不会crash。

**Comment by android-notes** [comment]
app启动时请求后端接口，决定要不要装载，何时装载卸载 @qingguoguo
