### ISSUE TITLE
程序卡死，无响应

### ISSUE THREAD

**Issue by YuedongMa** [android-notes/Cockroach#17]
我在fragment中添加了一个控件，没有对这个控件进行findViewById操作，然后设置他的点击事件，运行后启动程序就卡死半天无响应结束了，该怎么做呢，我在mainAcitivty中进行安装和卸载

**Comment by android-notes** [comment]
程序没有卡死，是由于act生命周期执行不完整导致的，Cockroach只能保证不crash，并不知道发生异常时该怎么补救，Cockroach很多时候可以有效提升用户体验 @YuedongMa
