### ISSUE TITLE
com.wanjian.cockroach.ExceptionHandler#onMayBeBlackScreen

### ISSUE THREAD

**Issue by wangzhumo** [android-notes/Cockroach#22]
请问你在哪里判断的回调  ？
onMayBeBlackScreen

MayBe   &  new RuntimeException("black screen")

如果真的是 maybe  这样好么？

**Comment by android-notes** [comment]
view绘制过程（measure，layout，draw）中抛出异常可能会导致什么都不显示，这种情况会调用onMayBeBlackScreen。比如当前A act中的recyclerview中bindview时抛出了异常，这时虽然该recyclerview还可以滚动，点击，并且可以返回到上一个act时，但如果从A act打开新的act B，然后关闭B返回A时，可能A就什么都不显示了，并且这时再次按返回按键的话可能无法关闭A，不好判断到底是哪个act中的view抛出的异常，所以建议杀进程 @wangzhumo

**Comment by wangzhumo** [comment]
非常感谢你的回复。

**Comment by android-notes** [comment]
不客气 😊
