### ISSUE TITLE
捕获所有崩溃

### ISSUE THREAD

**Issue by liulance** [android-notes/Cockroach#24]
你好，能否捕获所有崩溃？现在还是会有些崩溃上报到bugly，比如oom等，让bugly上的崩溃率减少。谢谢

**Comment by android-notes** [comment]
为什么要让bugly上的减少些呢？ @liulance

**Comment by wangchang163** [comment]
我想说，怎么能让友盟或者bugly捕获异常呢

**Comment by android-notes** [comment]
先初始化Cockroach，再初始化友盟或bugly @wangchang163

**Comment by wangchang163** [comment]
> 先初始化Cockroach，再初始化友盟或bugly @wangchang163

you are right，友盟有手动上传日志的接口可以调用，thanks

**Comment by guolianggh** [comment]
可以捕获so库抛出的异常吗

**Comment by android-notes** [comment]
不可以  @guolianggh
