### ISSUE TITLE
能支持Android P 吗？

### ISSUE THREAD

**Issue by YuYongzhi** [android-notes/Cockroach#25]
目前的在Android P 以下的手机上，在activity 的生命周期报错时，都可正常拦截到，且可以正常finish 打开的activity。但是在Android P 的手机上，会黑屏。有计划修复吗？

**Comment by android-notes** [comment]
感谢反馈，近期会修复 @YuYongzhi

**Comment by android-notes** [comment]
已修复 @YuYongzhi
