### ISSUE TITLE
一处问题需要处理一下

### ISSUE THREAD

**Issue by newlai913** [android-notes/Cockroach#26]
java.lang.IllegalStateException
The specified child already has a parent. You must call removeView() on the child's parent first.
com.wanjian.cockroach.Cockroach$2.boolean handleMessage(android.os.Message)(Unknown Source:76)
报错信息是这样的

**Comment by android-notes** [comment]
所有异常的错误堆栈都会包含com.wanjian.cockroach.Cockroach$2.boolean handleMessage，先确认下是否把一个view 同时加进了两个viewgroup中。

Cockroach只能保证不crash，但如果原本导致崩溃的异常被Cockroach捕获到后 可能还会出现各种奇奇奇怪的问题，这个问题可能是由于之前的异常没有终止进程，也可能是确实是你的代码逻辑问题导致的


@newlai913
