### ISSUE TITLE
弱弱的问一句这个库怎么集成到项目啊

### ISSUE THREAD

**Issue by avenue2013** [android-notes/Cockroach#28]
弱弱的问一句这个库怎么集成到项目啊，使用gradle还是要下载包啊

**Comment by feisher** [comment]
@avenue2013 最简单的直接复制群主 app下面 com/wanjian/codkroach  复制到自己的项目里面就可以了，当然你可以随便自己起个文件夹名字

**Comment by android-notes** [comment]
是的，可以直接复制代码，这块很灵活，也不一定非要按照我的代码实现，了解原理了你也可以自己实现一下  @avenue2013
