### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by for7GG** [android-notes/Cockroach#3]
对于集成了腾讯bugly反馈的app也可以吗？需要做什么处理？

**Comment by android-notes** [comment]
bugly内部应该也会设置Thread.setDefaultUnCatchExceptionHandler，所以要在bugly前初始化Cockroach，以便让bugly优先捕获异常，然后再让cockroach捕获异常。理论上应该兼容bugly，你可以接入后测试一下

**Comment by shuxinhuang** [comment]
经过测试。初始化Cockroach步骤无论是在bugly前，还是在bugly 之后，bugly都获取不到异常信息。这种情况，怎么解决

**Comment by android-notes** [comment]
bugly实现原理不清楚，我的理解如下：cockroach导致主线程始终不会崩溃，所以bugly始终无法捕获到主线程异常信息，但子线程的异常可以被bugly捕获到（前提是要在Cockroach初始化后再初始化bugly，Cockroach只能初始化一次，防止Cockroach把bugly的默认异常处理器覆盖掉，bugly中应该有主动上报异常的功能，可以把void handlerException(final Thread thread, final Throwable throwable)中的throwable上报到bugly）
