### ISSUE TITLE
android 9.0 照样崩溃  三星s8+

### ISSUE THREAD

**Issue by mrme2014** [android-notes/Cockroach#31]
在application#oncreate  初始化2.0版本，没有其他初始化代码的
```
Cockroach.install()
```

在mainActivity#onCreate手动 
```
 throw new RuntimeException("测试测试测试测试测试测试测试测试测试测试测试测试");
```
APP照样崩溃

**Comment by android-notes** [comment]
具体什么现象，进程还活着吗，在Android9.0以下的版本呢   @mrme2014

**Comment by 18811727185** [comment]
估计是Cockroach还没初始化成功，可以尝试在attachbaseContext去初始化看看，不过不包准

**Comment by nxnyk** [comment]
怎么初始化的。。有没有2.0的地址啊
