### ISSUE TITLE
生命周期出现异常，bugly无法上报

### ISSUE THREAD

**Issue by xchdong** [android-notes/Cockroach#33]
Cockroach放在第一个初始化（在bugly之前）在页面启动过程当中触发异常（测试用的是：Color.parseColor("534")）。会进入安全模式，onUncaughtExceptionHappened方法会调用，但是bugly无法上报，只能手动上报错误。有办法可以优化吗？

**Comment by android-notes** [comment]
按理来说不会影响bugly的，bugly也是通过uncatchexceptionhandler来捕获java异常的，可以提供下代码或者小demo吗 @xchdong

**Comment by CWTakiku** [comment]
这个解决了嘛

**Comment by gucuncun** [comment]
@xchdong 你的问题解决了吗，我这也是一样，bugly无法上报错误

**Comment by android-notes** [comment]
第一次异常可以上报，之后的异常不会上报，当然也可以上报。不过之后的异常可能是由于上一个异常引起的，所以没让bugly上报 @xchdong @gucuncun

**Comment by a773091614** [comment]
遇到了同样的问题...

**Comment by LiWeiQiangAndroid** [comment]
主动上报可以吧
