### ISSUE TITLE
ANR_EXCEPTION

### ISSUE THREAD

**Issue by cikichen** [android-notes/Cockroach#4]
install方法里面的Looper.loop();会导致这个问题

**Comment by android-notes** [comment]
什么情况下发生ANR，有日志吗

**Comment by cikichen** [comment]
没有日志，没有uninstall，只在application的oncreate里面install了

**Comment by android-notes** [comment]
必现吗，有没有使用bugly等第三方sdk，有没有设置过Thread.setDefaultUnCatchExceptionHandler

**Comment by cikichen** [comment]
@android-notes 出现很多吧，没有使用第三方sdk，没有设置Thread.setDefaultUnCatchExceptionHandler

**Comment by android-notes** [comment]
可以把你的代码或者demo发给我看一下吗？app弹框提示ANR还是没弹，但没法点击等操作而且屏幕上什么都没显示。是不是你在activity初始化时抛出了异常

**Comment by cikichen** [comment]
@android-notes 现象不明，后台监测到的

**Comment by android-notes** [comment]
怎么监测到的，用什么监测的

**Comment by android-notes** [comment]
是不是为Looper设置了setMessageLogging ，并在Printer的println方法中监测的anr？

**Comment by cikichen** [comment]
@android-notes 没有

**Comment by printdollor** [comment]
没用第三方，那就是说不同的rom会有不同的反应吧。。 ？

**Comment by android-notes** [comment]
理论上基本不会存在兼容问题，怎么监测到的ANR，用什么监测的，可不可以说清楚点

**Comment by zengd0** [comment]
在一个Activity中，定义一个成员Object mObj;
不初始化mObj，然后调用mObj的任意方法，比如mObj.equals("test");会出现ANR

**Comment by android-notes** [comment]
这不是ANR，是由于activity初始化抛出了异常，导致activity生命周期没有执行完整，所以导致了什么都不显示，其实这时主线程是没有被阻塞的，你如果在activity的onCreate中new Handler().post(runnable),并在Runnable的run中调用mObj的任意方法的话就不会出现什么都不显示了，Cockroach一般可以用在listview或recyclerview等这类延时加载view的控件中，当这些控件的adapter中抛出异常时，只是导致后面的ui不显示，但已经显示的控件的点击等还是可以响应的。activity crash大部分是由于服务端返回数据后导致的，这时activity通常已经初始化完成，那么这时如果抛出了异常只会导致ui不显示，其他的ui比如标题栏等还是可以正常显示的 @zengd0
