### ISSUE TITLE
error信息不完善

### ISSUE THREAD

**Issue by zqy789** [android-notes/Cockroach#42]
在异常之后，我通过我通过Throwable获取到 ‘ArithmeticException: divide by zero’，请问我可以通过什么办法在异常时将错误的类信息比如'ScpDetailActivity$onViewCreated$1.onClick(ScpDetailActivity.kt:44)'，从而让我传到后台，方便问题的定位

**Comment by android-notes** [comment]
String err = android.util.Log.getStackTraceString(throwable); @zqy789
