### ISSUE TITLE
只在Appcation里面安装 然后不卸载会有问题吗

### ISSUE THREAD

**Issue by xiongwenzhi** [android-notes/Cockroach#5]
只在Appcation里面安装 然后一直不卸载会有问题吗？

**Comment by android-notes** [comment]
建议在进入有crash的activity前装载，退出后卸载

**Comment by xiongwenzhi** [comment]
那还是每个activity都得写代码吗

**Comment by android-notes** [comment]
可以全局初始化一次，最好时发现某个activity频繁crash时再装载

**Comment by jeffery812** [comment]
我觉得在Application里面安装，不卸载是可以的。这样Cockroach会一直伴随着Application, Application不在的话也无所谓卸载了。

**Comment by android-notes** [comment]
如果你能做好善后 工作的话也是可以的，但若activity生命周期回调中抛出了异常就会导致黑屏的，而且还有可能导致各种奇怪的现象，建议开启后不影响用户体验的情况下开启 @zhihuitang

**Comment by jeffery812** [comment]
嗯，我自己在我的app中用上了，在application 中安装，不管卸载了。因为我觉得以前直接粗暴的退出也比黑屏好不到哪里去。
