### ISSUE TITLE
经常报这种错，有解决方法不？

### ISSUE THREAD

**Issue by seuercc** [android-notes/Cockroach#55]
"main" prio=5 tid=1 Native
 | group="main" sCount=1 dsCount=0 flags=1 obj=0x75849b50 self=0x70a1015c00
 | sysTid=21589 nice=-10 cgrp=default sched=0/0 handle=0x7127948548
 | state=S schedstat=( 21136584986 342317179 9521 ) utm=1907 stm=206 core=7 HZ=100
 | stack=0x7fce530000-0x7fce532000 stackSize=8MB
 | held mutexes=
 kernel: (couldn't read /proc/self/task/21589/stack stderr:Permission denied)
 native: #00 pc 000000000007074c /system/lib64/libc.so (__epoll_pwait+8)
 native: #01 pc 0000000000013fbc /system/lib64/libutils.so (android::Looper::pollInner(int)+148)
 native: #02 pc 0000000000013e8c /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
 native: #03 pc 000000000012bd80 /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
 at android.os.MessageQueue.nativePollOnce(Native method)
 at android.os.MessageQueue.next(MessageQueue.java:382)
 at android.os.Looper.loop(Looper.java:270)

**Comment by seuercc** [comment]
@android-notes

**Comment by android-notes** [comment]
这个和cockroach没关系吧 @seuercc
