### ISSUE TITLE
接入后Application有被反复启动的循环

### ISSUE THREAD

**Issue by kartyjoin** [android-notes/Cockroach#64]
从其他埋点信息发现，Application.onCreate() 调用次数翻了几倍，跟踪埋点变化数据的对应版本发现是接入Cockrooach后开始升高的，有些设备每隔5秒就会走一次Application.onCreate()，猜测进入了某种crash的循环，设备不断启动App，但暂无法复现

**Comment by kartyjoin** [comment]
@android-notes

**Comment by feisher** [comment]
@kartyjoin 这个和他这个库没啥关系，建议你同时接入bugly 或者其他异常监控，从根源上找到是那里出了异常导致闪退，，，这个库只是要闪退的时候捕获一下，可以执行重新拉起应用，但并不能解决异常
